### ISSUE TITLE
Build fails with clang-19: no member named 's' in 'vec<T, N>'

### ISSUE THREAD

**Issue by yurivict** [kfrlib/kfr#236] opened 2024-11-03 19:40 UTC
```
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/src/dsp/biquad.cpp:27:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/biquad.hpp:28:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/filter.hpp:28:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/basic_expressions.hpp:28:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/expression.hpp:29:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/../simd/read_write.hpp:28:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/../simd/impl/read_write.hpp:28:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/../simd/impl/../shuffle.hpp:28:
In file included from /wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/../simd/impl/../mask.hpp:28:
/wrkdirs/usr/ports/math/kfr/work/kfr-6.0.3/include/kfr/dsp/../base/../simd/impl/../vec.hpp:499:15: error: no member named 's' in 'vec<T, N>'
  499 |         this->s[index] = s;
      |         ~~~~  ^
1 error generated.
```

Version: 6.0.3
FreeBSD 15

**Comment by dancazarin** [comment] 2024-11-03 19:42
Duplicate of #234 , fixed in the latest release (6.0.4)

**Closed** 2024-11-03 19:48 UTC
Labels: duplicate
